apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-service
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
      nodePort: 30002
  selector:
    service: udaconnect-connection-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection-service
  name: udaconnect-connection-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection-service
  template:
    metadata:
      labels:
        service: udaconnect-connection-service
    spec:
      containers:
        - image: excitedelektron/uda-connect-connection-microservice:latest
          name: udaconnect-connection-service
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
            - name: LOCATION_SERVICE_ENDPOINT
              value: "10.42.0.61:31001"
            - name: PERSONS_SERVICE_ENDPOINT
              value: "10.42.0.66:31000"
      restartPolicy: Always
