# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\"J\n\x0fLocationRequest\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"l\n\x0fLocationMessage\x12\x11\n\tlongitude\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\t\x12\x15\n\rcreation_time\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\x12\x11\n\tperson_id\x18\x05 \x01(\x05\"7\n\x10LocationsMessage\x12#\n\tlocations\x18\x01 \x03(\x0b\x32\x10.LocationMessage2H\n\x0fLocationService\x12\x35\n\x0cGetLocations\x12\x10.LocationRequest\x1a\x11.LocationsMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONREQUEST._serialized_start=18
  _LOCATIONREQUEST._serialized_end=92
  _LOCATIONMESSAGE._serialized_start=94
  _LOCATIONMESSAGE._serialized_end=202
  _LOCATIONSMESSAGE._serialized_start=204
  _LOCATIONSMESSAGE._serialized_end=259
  _LOCATIONSERVICE._serialized_start=261
  _LOCATIONSERVICE._serialized_end=333
# @@protoc_insertion_point(module_scope)
