FROM python:3.7-alpine

RUN apk add --no-cache gcc musl-dev linux-headers geos libc-dev postgresql-dev
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

EXPOSE 5000

WORKDIR /udacity/nd064-c2-message-passing-projects-starter/modules/person_microservice

CMD [ "/bin/sh" ]