# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\"\x0b\n\tNoRequest\"X\n\rPersonMessage\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\"1\n\x0ePersonsMessage\x12\x1f\n\x07persons\x18\x01 \x03(\x0b\x32\x0e.PersonMessage2<\n\rPersonService\x12+\n\nGetPersons\x12\n.NoRequest\x1a\x0f.PersonsMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOREQUEST._serialized_start=16
  _NOREQUEST._serialized_end=27
  _PERSONMESSAGE._serialized_start=29
  _PERSONMESSAGE._serialized_end=117
  _PERSONSMESSAGE._serialized_start=119
  _PERSONSMESSAGE._serialized_end=168
  _PERSONSERVICE._serialized_start=170
  _PERSONSERVICE._serialized_end=230
# @@protoc_insertion_point(module_scope)
